--<ScriptOptions statementTerminator=";"/>

CREATE SCHEMA "Schema";

CREATE TABLE "Schema"."ATTEMPTS" (
		"USERNAME" CHAR(20) NOT NULL, 
		"PASSWORD" CHAR(12) NOT NULL, 
		"NUM_ATTEMPTS" INTEGER
	)
	DATA CAPTURE NONE;

CREATE TABLE "Schema"."ATTENDENCE" (
		"EVENT_ID" CHAR(2) NOT NULL, 
		"CANDIDATE_ID" CHAR(2) NOT NULL, 
		"DESCRIPTION" CHAR(100)
	)
	DATA CAPTURE NONE;

CREATE TABLE "Schema"."CANDIDATES" (
		"CANDIDATE_ID" CHAR(2) NOT NULL, 
		"FIRST_NAME" CHAR(30), 
		"LAST_NAME" CHAR(30), 
		"STREET_ADDRESS" CHAR(50), 
		"CITY" CHAR(25), 
		"STATE" CHAR(2), 
		"ZIP_CODE" CHAR(5), 
		"EMAIL_ADDRESS" CHAR(30), 
		"PHONE_NUMBER" CHAR(12), 
		"MAJOR" CHAR(25), 
		"MINOR" CHAR(30), 
		"SCHOOL" CHAR(30), 
		"GRADUATION_YEAR" CHAR(4), 
		"ACTIVE_STATUS" CHAR(2)
	)
	DATA CAPTURE NONE;

CREATE TABLE "Schema"."EVENTS" (
		"EVENT_ID" CHAR(2) NOT NULL, 
		"EVENT_NAME" CHAR(50), 
		"DESCRIPTION" CHAR(100), 
		"SCHOOL" CHAR(30), 
		"DATE" DATE, 
		"ACTIVE_STATUS" CHAR(2), 
		"RECRUITER_ID" CHAR(2) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "Schema"."EVENTS_X_CANDIDATES" (
		"EVENT_ID" CHAR(2) NOT NULL, 
		"CANDIDATE_ID" CHAR(2) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "Schema"."RECRUITERS" (
		"RECRUITER_ID" CHAR(2) NOT NULL, 
		"FIRST_NAME" CHAR(30), 
		"LAST_NAME" CHAR(30), 
		"STREET_ADDRESS" CHAR(50), 
		"CITY" CHAR(30), 
		"STATE" CHAR(2), 
		"ZIP_CODE" CHAR(5), 
		"PHONE_NUMBER" CHAR(12), 
		"EMAIL_ADDRESS" CHAR(30)
	)
	DATA CAPTURE NONE;

CREATE TABLE "Schema"."USER_LOGIN" (
		"USERNAME" CHAR(20) NOT NULL, 
		"PASSWORD" CHAR(12) NOT NULL, 
		"RECRUITER_ID" CHAR(2) NOT NULL
	)
	DATA CAPTURE NONE;

ALTER TABLE "Schema"."CANDIDATES" ADD CONSTRAINT "CANDIDATES_PK" PRIMARY KEY
	("CANDIDATE_ID");

ALTER TABLE "Schema"."EVENTS" ADD CONSTRAINT "EVENTS_PK" PRIMARY KEY
	("EVENT_ID");

ALTER TABLE "Schema"."EVENTS_X_CANDIDATES" ADD CONSTRAINT "EVENTS_X_CANDIDATES_PK" PRIMARY KEY
	("EVENT_ID", 
	 "CANDIDATE_ID");

ALTER TABLE "Schema"."RECRUITERS" ADD CONSTRAINT "RECRUITERS_PK" PRIMARY KEY
	("RECRUITER_ID");

ALTER TABLE "Schema"."USER_LOGIN" ADD CONSTRAINT "USER_LOGIN_PK" PRIMARY KEY
	("USERNAME", 
	 "PASSWORD");

ALTER TABLE "Schema"."ATTEMPTS" ADD CONSTRAINT "ATTEMP_USER_LOG_FK" FOREIGN KEY
	("USERNAME", 
	 "PASSWORD")
	REFERENCES "Schema"."USER_LOGIN"
	("USERNAME", 
	 "PASSWORD");

ALTER TABLE "Schema"."ATTENDENCE" ADD CONSTRAINT "ATTENDENC_EVENT_FK" FOREIGN KEY
	("EVENT_ID")
	REFERENCES "Schema"."EVENTS"
	("EVENT_ID");

ALTER TABLE "Schema"."ATTENDENCE" ADD CONSTRAINT "ATTENDE_CANDIDA_FK" FOREIGN KEY
	("CANDIDATE_ID")
	REFERENCES "Schema"."CANDIDATES"
	("CANDIDATE_ID");

ALTER TABLE "Schema"."EVENTS" ADD CONSTRAINT "EVENT_RECRUITER_FK" FOREIGN KEY
	("RECRUITER_ID")
	REFERENCES "Schema"."RECRUITERS"
	("RECRUITER_ID");

ALTER TABLE "Schema"."EVENTS_X_CANDIDATES" ADD CONSTRAINT "EVENTS_CANDIDATES_FK" FOREIGN KEY
	("EVENT_ID")
	REFERENCES "Schema"."EVENTS"
	("EVENT_ID");

ALTER TABLE "Schema"."EVENTS_X_CANDIDATES" ADD CONSTRAINT "EVENTS_CANDIDATES_FK1" FOREIGN KEY
	("CANDIDATE_ID")
	REFERENCES "Schema"."CANDIDATES"
	("CANDIDATE_ID");

ALTER TABLE "Schema"."USER_LOGIN" ADD CONSTRAINT "USER_LO_RECRUIT_FK" FOREIGN KEY
	("RECRUITER_ID")
	REFERENCES "Schema"."RECRUITERS"
	("RECRUITER_ID");

